# Generated by Django 3.1.3 on 2021-01-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210104_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='album',
        ),
    ]
